In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("play_tennis.csv")

In [3]:
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
data.drop(columns=['day'] , inplace=True)

In [5]:
data.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [12]:
data.shape

(14, 5)

In [6]:
## problem 1 
# outlook = sunny . temp = hot , Humidity = high , wind = weak
# play or not play!

In [7]:
# training
# lookup table (set of probablites
#  testing
# prediction

In [8]:
# p(yes)
# p(no)

In [11]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [13]:
py = 9/14
pn = 5/14

In [14]:
print(py)

0.6428571428571429

In [15]:
print(pn)

0.35714285714285715

In [16]:


# outlook 
pd.crosstab(data['outlook'] , data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [17]:
pon = 0     # probability  of overcast no 
prn = 2/5     # prob of rain no
psn = 3/5     # prob suny no

poy = 4/9   # prob of overcast yes 
pry=3/9     # prob of rain yes 
psy= 2/9    # prob of sunny yes

In [18]:
# temp 

pd.crosstab(data['temp'] , data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [19]:
PCoolNo =  1/5  # prob of cool  no
PHotNo =  2/5    # prob of hot no
PMildNo = 2/5    # prob of mild no
 

PCoolYes = 3/9   # prob of  cool yes 
PHotYes = 2/9    # prob of hot yes 
PMildYes = 4/9    # prob of mild yes

In [20]:




# Humidity

pd.crosstab(data['humidity'] , data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [21]:
PHighNo = 4/5  # prob of high no
PNormalNo = 1/5   # prob of normal no


PHighYes = 3/9     # prob of high yes 
PNormalYes = 6/9    # prob of normal yes

In [22]:



# wWind


pd.crosstab(data['wind'] , data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [24]:
PStrongNo = 3/5   # prob of strong no
PWeakNo = 2/5    # prob of weak no


PStrongYes = 3/9  # prob odf strong yes
PWeakYes = 6/9   # prob of weak yes

In [26]:
# outlook = sunny . temp = hot , Humidity = high , wind = weakabs   by naive bayes algo




Pyes = py*psy*PHotYes*PHighYes*PWeakYes

print(Pyes)

0.007054673721340388

In [27]:
Pno = pn*psn*PHotNo*PHighNo*PWeakNo

print(Pno)

0.02742857142857143

In [28]:
# so prediction of problem is '  No play  '